# Generated by Django 5.0.1 on 2024-01-29 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playlists", "0002_music_singer_alter_music_length_in_seconds"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="musics",
            field=models.ManyToManyField(
                related_name="playlists", to="playlists.music"
            ),
        ),
    ]
